name: validate

on:
  pull_request:

jobs:
  check:
    runs-on: docker
    steps:
      - uses: actions/checkout@v4
      - uses: https://github.com/pnpm/action-setup@v6
        with:
          version: 10
      - run: pnpm i && pnpm --package=typescript dlx tsc --noEmit
