import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import Config from "./ConfigHandler.js";
import { log } from "./Logger.js";

/**
 * The two arrows and the spinner Grytcord draws its own furniture with, as
 * Discord application emojis so they work in every guild the bridge touches.
 *
 * Gryt needs no counterpart: a reply there is drawn as a quote line, and the
 * "still working on it" placeholder only exists on the Discord side, because a
 * webhook message on Gryt cannot be edited afterwards.
 */

const ASSET_DIR = path.join(
  path.dirname(fileURLToPath(import.meta.url)),
  "..",
  "data",
);

/** @type {any} */
let cached = null;

function configPath() {
  return path.join(Config.DataFolderPath, "grytcord.json");
}

function readStored() {
  try {
    return JSON.parse(fs.readFileSync(configPath(), "utf-8"));
  } catch {
    return {
      autoGenerated:
        "This file is automatically generated by Grytcord. Please do not touch it!",
    };
  }
}

/**
 * @param {import("discord.js").Client} discordClient
 * @param {string} name
 * @param {string} file
 */
async function ensureAppEmoji(discordClient, name, file) {
  const existing = await discordClient.application?.emojis.fetch();
  const found = existing?.find((x) => x.name === name);
  if (found) return found.id;

  const assetPath = path.join(ASSET_DIR, file);
  if (!fs.existsSync(assetPath)) return null;

  try {
    const created = await discordClient.application?.emojis.create({
      attachment: fs.readFileSync(assetPath),
      name,
    });
    return created?.id ?? null;
  } catch (e) {
    log("DISCORD", `Could not create the ${name} application emoji`, e);
    return null;
  }
}

/**
 * @param {import("discord.js").Client} discordClient
 */
export async function ensureBotEmojis(discordClient) {
  const stored = readStored();

  if (!stored.discordReplyEmoji?.replyL || !stored.discordReplyEmoji?.replyR) {
    log("META", "Setting up Grytcord's reply emojis...");
    const replyL = await ensureAppEmoji(discordClient, "reply_l", "reply-l.webp");
    const replyR = await ensureAppEmoji(discordClient, "reply_r", "reply-r.webp");
    stored.discordReplyEmoji = { replyL, replyR };
  }

  try {
    fs.mkdirSync(Config.DataFolderPath, { recursive: true });
    fs.writeFileSync(configPath(), JSON.stringify(stored, null, 2));
  } catch (e) {
    log("META", "Could not write grytcord.json", e);
  }

  cached = stored;
  return stored;
}

/** What `ensureBotEmojis` last worked out, for the handlers to draw with. */
export function botEmojiConfig() {
  if (!cached) cached = readStored();
  return cached;
}

/**
 * The little "↩" pair, or a plain arrow when the emojis could not be created.
 */
export function replyMarker() {
  const config = botEmojiConfig();
  const left = config?.discordReplyEmoji?.replyL;
  const right = config?.discordReplyEmoji?.replyR;
  if (left && right) return `<:reply_l:${left}><:reply_r:${right}>`;
  return "↪";
}
